const bcrypt=require('bcrypt')
const postAdmin={
    Admin:async (req,res)=>({
        email:req.body.email,
        password:await bcrypt.hash(req.body.password,10)
    }),
    About:(req,res)=>({
        description:req.body.description,
    }),
    Contact:(req,res)=>({
        name:req.body.name,
        phone:req.body.phone,
        github:req.body.github,
        linkedin:req.body.linkedin,
        gmail:req.body.gmail
    }),
    Technologies:(req,res)=>({
        name:req.body.name,
        rate:req.body.rate
    }),
    Experience:(req,res)=>({
        cardType:req.body.cardType,
        title:req.body.title,
        description:req.body.description,
        date:req.body.date
    }),
    Education:(req,res)=>({
        cardType:req.body.cardType,
        title:req.body.title,
        description:req.body.description,
        date:req.body.date
    }),
    Project:(req,res)=>({
        cardType:req.body.cardType,
        title:req.body.title,
        description:req.body.description,
        github:req.body.github,
        date:req.body.date
    }),
    Project:(req,res)=>({
        cardType:req.body.cardType,
        name:req.body.name,
        gmail:req.body.gmail,
        phone:req.body.phone,
        referanceText:req.body.referanceText,
        nick:req.body.nick
    }),
}
module.exports={postAdmin}